print('digite algo:')
algo = input()
print('o tipo primitivo desse valor e', type(algo))
print('so tem espaços'algo.isspace())
print('e um numero'algo.isnumeric())
print('e alfabetico'algo.isalpha())
print('e alfanumerico'algo.isalnum())
print('so tem maiusculas'algo.isupper())
print('so tem minusculas'algo.islower())
print('esta capitalizada'algo.istitle())
